### ISSUE TITLE
GetProjectAsync not work

### ISSUE THREAD

**Issue by trinhbaan24** [ats124/backlog4net#94]
@ats124 
now, backlog4net not working

error: backlog api request failed
Backlog4net.BacklogApiException' occurred in XXX.exe but was not handled in user code

   場所 Backlog4net.Http.BacklogHttpClient.<Get>d__14.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Backlog4net.BacklogClientImpl.<Get>d__22.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 Backlog4net.BacklogClientImpl.<GetProjectAsync>d__93.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   場所 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by ats124** [comment]
Thanks for the report. I'll check it.

**Comment by ats124** [comment]
@trinhbaan24 I checked it but it worked in my environment. Does other methods work?

**Comment by trinhbaan24** [comment]
@ats124

this is my source code. other methods is not work too. does this code true?

`Imports Backlog4net
Imports Backlog4net.Api.Option
Imports Backlog4net.Conf

Module C00_E00XF
    '*******************************************************************************
#Region ""
#End Region
    '#Region "MAIN"
    Sub Main()
        Dim task = New Task(AddressOf ProcessDataAsync)
        ' Start and wait for task to end.
        task.Start()
        task.Wait()

        Console.ReadLine()
    End Sub

    Async Sub ProcessDataAsync()

        Dim conf As New BacklogJpConfigure("chiyotest") 'spaceKey
        conf.ApiKey = "ICESrRCu3LmGPNtJIwA6cyndnFsDNeiopFJP1QltR5rWB0RKvcCFiY9G7n1gKdrh"
        Dim backlogClient = New BacklogClientFactory(conf).NewClient()
        Try
            Dim project = Await backlogClient.GetProjectAsync("T_CHIYODA")
            Console.WriteLine("Please wait, processing find projectId")
            Dim projectId = project.Id

            Dim listIssue = Await backlogClient.GetIssuesAsync(New GetIssuesParams(projectId))
            Console.WriteLine("Please wait, processing")


            Console.WriteLine("Count: " + listIssue.Count.ToString)
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try

    End Sub`

**Comment by ats124** [comment]
@trinhbaan24

Your program worked in my environment.

The results are as follows
``` console
Please wait, processing find projectId
Please wait, processing
Count: 20
```

However, asynchronous methods are incorrectly used, which may cause problems.

Can not set asynchronous method in Task constructor argument.
```vb
Dim task = New Task(AddressOf ProcessDataAsync)
```

Please try to see if the following program works properly.
```vb
    Sub Main()
        ProcessDataAsync().Wait()
        Console.ReadLine()
    End Sub

    Async Function ProcessDataAsync() As Task
        Dim conf As New BacklogJpConfigure("chiyotest") 'spaceKey
        conf.ApiKey = "ICESrRCu3LmGPNtJIwA6cyndnFsDNeiopFJP1QltR5rWB0RKvcCFiY9G7n1gKdrh"
        Dim backlogClient = New BacklogClientFactory(conf).NewClient()
        Try
            Dim project = Await backlogClient.GetProjectAsync("T_CHIYODA")
            Console.WriteLine("Please wait, processing find projectId")
            Dim projectId = project.Id

            Dim listIssue = Await backlogClient.GetIssuesAsync(New GetIssuesParams(projectId))
            Console.WriteLine("Please wait, processing")


            Console.WriteLine("Count: " + listIssue.Count.ToString)
        Catch ex As Exception
            Console.WriteLine(ex.Message)
        End Try
    End Function
```

**Comment by trinhbaan24** [comment]
[Backlog4net.zip](https://github.com/ats124/backlog4net/files/2212091/Backlog4net.zip)
@ats124

thank for your comfirm.
However,it not worked in my environment. 
![image](https://user-images.githubusercontent.com/41181227/42977335-c453386c-8bf0-11e8-8f28-4957328bf0f1.png)

can you send to me your Backlog4net.dll?
please!

**Comment by ats124** [comment]
@trinhbaan24 
I will share the Visual Studio 2017 Project with you built and executed your source code.

Please download here.
https://www.dropbox.com/s/onar9ar8oatck6n/ConsoleApp1.zip?dl=1

**Comment by trinhbaan24** [comment]
@ats124 

thank you very much
it is worked.

**Comment by ats124** [comment]
@trinhbaan24 
That's good.
I close this issue.
